### ISSUE TITLE
Profiles Table Migration Error 

### ISSUE THREAD

**Issue by JohnstoneDev** [Omari-Elizabeth/moringa-alumni-backend#14]
@Omari-Elizabeth , @JamesKibathi . There is an error with displaying the profile for a user. The table appears to have disappeared from the schema? Trying to run a rollback of the last migration raises this error 
![image](https://user-images.githubusercontent.com/78861332/212009855-97b743b7-e110-4361-8ea1-d00bf61984d7.png)

**Comment by Omari-Elizabeth** [comment]
I have gone through the error. When you pull, the migrations and the schema should be up to date
